routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/



Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/', 'PaymentController@index');
Route::post('/billpayment/receipt','PaymentController@receipt');
Route::get('/billimport/progress-check/{bill_date}/{count}', array('uses' => 'BillImportController@progressCheck', 'as' => 'billimport.progressCheck'));

Route::get('/terms', 'PaymentController@terms');
Route::get('/privacy', 'PaymentController@privacy');
Route::get('/refund', 'PaymentController@refund');
Route::get('/contact', 'PaymentController@contact');
Route::post('/billpayment/pay', 'PaymentController@query');
Route::post('/billpayment/query', 'PaymentController@store');
Route::get('/querypage', 'PaymentController@queryPage');
Route::post('/billpayment/testURL', 'PaymentController@testUrl');
// Route::get('history_list', 'PaymentController@history_list');
// Route::get('history', 'PaymentController@history_list');

Route::get('/paymentlock','LockController@lock');
Route::get('/lockindex', 'LockController@index');

Route::post('/billpayment/gGwXi', 'PaymentController@getbill');
Route::get('/billpayment/{div}', 'PaymentController@billpayment');

Route::resource('/billpayment', 'PaymentController');

Route::post('/billpayment_import/query', 'PaymentController@query');
Route::post('store_import', 'PaymentController@store_import');
Route::get('/billpayment_import/{div}', 'PaymentController@billpayment_import');

Route::resource('/billpayment_import', 'PaymentController');

Route::post('/billimport','BillImportController@index');
Route::post('/billimport/importserver','BillImportController@import_server');
Route::resource('billcollections','BillCollectionsController');
Route::get('importExport','BillImportController@importExport');
Route::get('/download', 'BillImportController@download');
Route::post('importExcel', 'BillImportController@importExcel');
Route::get('downloadExcel/{type}', 'BillImportController@downloadExcel');
Route::resource('billimport','BillImportController');
Route::get('correction','BillImportController@billcorrection');


Route::get('transaction/count', 'TransactionsController@index');
Route::get('transaction/history', 'TransactionsController@create');
Route::resource('/profiles','ProfileController');

app/Http/Controllers/BillImportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\BillItem;
use App\Division;
use App\BillCollections;
use Excel;
use DB;
use Auth;

class BillImportController extends Controller
{
    
   
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        abort(403,'UN-AUTHORISED ACTION');
        return view('billimport.importbills');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function update(Request $request, $id)
    {
       $consumer = BillItem::find($id);
      
       BillItem::where('id','=',$id)
                    ->update(['bill_amt' => $request->amount]);
        $success='Bill amount for ' . $consumer['C_CODE'].' has been updated';
        \Session::flash('success',$success);

        return redirect('/correction');
    }

    public function billcorrection(Request $request)
    {
        if(Auth::user()->email == 'hlira@mail.com' || Auth::user()->email == 'admin@mail.com')
        {

         
            $bill_date = BillItem::count();

            if($bill_date > 0){
                $date = BillItem:: orderBy( 'BILL_DATE' )->first();
                for ( $i = date( 'Y', strtotime( $date->BILL_DATE ) ); $i <= date( 'Y' ); $i ++ ) {
                    $year[ $i ] = $i;
                }
                $yearAll     = [ '' => 'All Year' ] + $year; 
            }
            else{
                $yearAll = ['' => 'All Year'];
            }

            $months = [
                '1' => 'January',
                '2' => 'February',
                '3' => 'March',
                '4' => 'April',
                '5' => 'May',
                '6' => 'June',
                '7' => 'July',
                '8' => 'August',
                '9' => 'September',
                '10' => 'October',
                '11' => 'November',
                '12' => 'December'];

            $monthAll = ['' => 'All Month'] + $months;

            // $consumer_no= (!empty($request['consumer_no']))?"AND consumer_no LIKE '%".$request['consumer_no']."%'":'';
            // $year= (!empty($request['year']))?"AND YEAR(`bill_date`) = '".$request['year']."'":'';
            // $month= (!empty($request['month']))?"AND MONTH(`bill_date`) = '".$request['month']."'":'';
            $history_list = BillItem::where(function($query) use ($request){
                                $query->where('C_CODE','LIKE','%'.$request['C_CODE'].'%');
                                $query->whereYear('BILL_DATE','LIKE','%'.$request['year'].'%');
                                $query->whereMonth('BILL_DATE','LIKE','%'.$request['month'].'%');
                                
                            })->orderBy( "id", "asc" )->paginate( 15 );
            return View('billimport.billcorrection',compact('history_list','yearAll','monthAll'));
       } 
       else
       {
            abort(403);
       }
       

    }
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function success($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
   
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function import_server(Request $request)
    {
        // shell_exec(\Artisan::call('import:bills'));
        if(!$request->bill_date)
        {
             $bill_date = "Bill Date field is required";
                    return view('billimport.importbills',compact('bill_date'));
        }
        else
        {
            if(BillItem::where('BILL_DATE','=',date('Y-m-d',strtotime($request->bill_date)))->count())
            {
                $bill_date = "Bill already imported for this month";
                    return view('billimport.importbills',compact('bill_date'));
            }
            
            $bill_date= date('d-M-y',strtotime($request->bill_date));
            $date_format='DD-MON-YY';
            $remote_db=config('oracle');
            $conn = oci_connect($remote_db['oracle']['username'], $remote_db['oracle']['password'],"//".$remote_db['oracle']['host']."/".$remote_db['oracle']['database']);
            $count_customer = oci_parse($conn, 'select count(c_code) as countResult from bill where bill_date= to_date(:bill_date, :date_format)');
            oci_bind_by_name($count_customer, ":bill_date", $bill_date);
            oci_bind_by_name($count_customer, ":date_format", $date_format);
            oci_execute($count_customer);
            $count_result=oci_fetch_array($count_customer,OCI_ASSOC);
            $count = $count_result["COUNTRESULT"];

            // dd($count);
            // if($count==0);
            // {

                
            //     $bill_date = "Nothing to import for this month";
            //         return view('billimport.importbills',compact('bill_date'));
            // }
            // \Artisan::call('import:bills');
            shell_exec('php ' . base_path('artisan') . ' import:bills '. $bill_date . ' > /dev/null 2>&1 &');
            shell_exec('php ' . base_path('artisan') . ' import:printbills > /dev/null 2>&1 &');
            return view('billimport.importprogress',compact('count','bill_date'));
      
        }
    }
    public function progressCheck($bill_date,$count)
    {
        $meta = BillItem::where('BILL_DATE','=',date('Y-m-d',strtotime($bill_date)))->count();
        $response = array(
                    'count' => $meta
                     );
        if ($meta==$count) {
            $success='Bills for '.date('d-M-y',strtotime($bill_date)).' has been imported successfully';
            \Session::flash('success',$success);
        }
        return $response;  
    }
    public function importExport()
    {
        if(auth::user()->id == 1){
            return view('billimport.importExport');
        } else {
            abort(403, 'Unauthorized action.');
        }
       
    }
    public function download()
    {
        //$billDate= BillCollections::groupBy('bill_date')->pluck('bill_date','bill_date');
        $billAll= [''=>'All Month',
                    '1' => 'January',
                    '2' =>'February',
                    '3' => 'March',
                    '4' => 'April',
                    '5' => 'May',
                    '6' => 'June',
                    '7' => 'July',
                    '8' => 'August',
                    '9' => 'September',
                    '10' => 'October',
                    '11' => 'Novermber',
                    '12' => 'December'
                    ];

        $check = BillCollections:: orderBy( 'PAID_DATE' )->count();
        if($check > 0){
                $date = BillCollections::orderBy( 'PAID_DATE' )->first();
                for ( $i = date( 'Y', strtotime( $date->PAID_DATE ) ); $i <= date( 'Y' ); $i ++ ) {
                    $year[ $i ] = $i;
                }
            }
        else{
            $year = [];
        }
        $yearAll     = [ '' => 'All Year' ] + $year;


        return view('billimport.download',compact('billAll','yearAll'));
    }

    public function downloadExcel(Request $request, $type)
        {
            $data = BillCollections::where( function ( $q ) use ( $request ) {
            
                 if ( $request->has( "payYear" ) && $request->payYear != null ) {
                    $q->where( DB::raw( "YEAR(`PAID_DATE`)" ), "=", $request->payYear );
                }

                if ( $request->has( "payMonth" ) && $request->payMonth != null ) {
                    $q->where( DB::raw( "MONTH(`PAID_DATE`)" ), "=", $request->payMonth );
                    $q->where( DB::raw( "STATUS" ), "=", "success" );
                }
            } )
                           ->get()
                           ->toArray();

            return Excel::create('bill_collection', function($excel) use ($data) {
                $excel->sheet('mySheet', function($sheet) use ($data)
                {
                    $sheet->fromArray($data);
                });
            })->download($type);
        }
        
    public function importExcel(Request $request)
        {
            //if($request->hasFile('import_file'))   

            if($request->file('import_file') !=null)  
            //2nd aug 2021 thanpuia
            {
                $chunk=0;
                $path = $request->file('import_file')->getRealPath();
                $data = Excel::load($path, function($reader) {})->get();
                if(!empty($data) && $data->count())
                {
                    foreach ($data->toArray() as $key => $value) 
                    {
                            if(!empty($value))
                            {
                                $chunk++;
                                $insert[] = [   
                                                'C_CODE' => $value['c_code'], 
                                                'BILL_NO' => $value['bill_no'],
                                                'C_NAME' => $value['c_name'], 

resources/views/billimport/billcorrection.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
         @if ($message = Session::get('success'))
                            <div class="alert alert-success" role="alert">
                            <center> {{ Session::get('success') }}</center>
                            </div>
                        @endif

                        @if ($message = Session::get('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ Session::get('error') }}
                            </div>
                        @endif
            
        </div>
        

    </div>
	<div class="row">
		<div class="col-md-12">
			  <div class="row">
                <div class="col-md-12">
                    {{Form::open(['url'=>'correction','method'=>'get'])}}  
                         <div class="col-md-3 form-group">
                            <?php 
                                if(isset($_GET['C_CODE'])){
                                    $consumer_no = $_GET['C_CODE'];
                                }
                                else{
                                    $consumer_no = NULL;
                                }
                            ?>
                            {!! Form::text('C_CODE', $consumer_no, array('class'=>'form-control', 'placeholder'=>'Customer Number'))!!}
                        </div> 
                        <div class="col-md-3 form-group">
                            <?php 
                                if(isset($_GET['year'])){
                                    $year = $_GET['year'];
                                }
                                else{
                                    $year = NULL;
                                }
                            ?>
                            {!! Form::select('year',$yearAll, $year,array('class'=>'form-control'))!!}
                        </div>
                        <div class="col-md-3 form-group">
                            <?php 
                                if(isset($_GET['month'])){
                                    $month = $_GET['month'];
                                }
                                else{
                                    $month = NULL;
                                }
                            ?>
                            {!! Form::select('month', $monthAll, $month,array('class'=>'form-control'))!!}
                        </div> 
                          <div class="col-md-3 form-group">
                            {!! Form::submit('Search', array('class'=>'btn btn-default btn-md search-btn'))!!}
                        </div>
                        {!!Form::close()!!}
                </div>
            </div>
                <div class="col-md-12">
					<div class="table-responsive">
					<strong>List Bill Collections</strong>
						<table class="table table-hover table-condensed" >
						<thead>
						  <tr>
						    <th height="38" align="left">#</th>
						    <th height="38" align="left" class="col-md-2">Customer Code</th>
						    <th height="38" align="left" class="col-md-2">Customer Name</th>
                            <th height="38" align="left" class="col-md-2">Bill Number</th>
						    <th height="38" align="left" class="col-md-2">Bill Date</th>
						    
						    <th height="38" align="left" class="col-md-1"> Bill Amount</th>
                            <th >Action</th>
						  </tr>
						  </thead>
						  <tbody>
						  	@foreach($history_list as $key => $bill)
							<tr bgcolor="">
						    <td height="25" align="left">{{ $key + $history_list->firstItem()}}</td>
                            <td height="25" align="left">{{ $bill['C_CODE'] }}</td>
						    <td height="25" align="left">{{ $bill['C_NAME'] }}</td>
                            <td height="25" align="left">{{ $bill['BILL_NO'] }}</td>
						    <td height="25" align="left">{{ $bill['BILL_DATE'] }}</td>
						   
                            
                                {{ Form::open(["url" =>route('billimport.update',$bill['ID']), "method" => "put", "class" => "form-vertical"])}}
                                    <td height="25" align="left"><input type="text" name="amount" value="{{ $bill['BILL_AMT']}}"></td>

                                   <td> <input type="submit" name="" value="Update" class="btn btn-xs btn-primary"></td>
                                {{Form::close()}}
                                                                   
                            
							@endforeach
						</tbody>
						</table>
						    {{ $history_list->appends(['C_CODE'=>$consumer_no,'year'=>$year,'month'=>$month])->links() }}
				</div>
			</div>
		</div>
	</div>
</div>


@endsection

resources/views/billimport/download.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Download Bill Collection</div>
                    <div class="panel-body">
                        {{Form::open(['url'=>'downloadExcel/csv','method'=>'get'])}}
                                &nbsp;&nbsp;
                                <div class="col-md-12">
                                    {!! Form::label('Payment Month','',['class'=>'col-md-4 control-label'])!!}
                                    <div class="col-md-6">
                                    {!! Form::select('payMonth',$billAll,'',['id'=>'payMonth','class'=>'form-control']) !!}
                                        @if($errors->has('payMonth'))
                                            <span class="text-danger">{{$errors->first('payMonth')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <br> &nbsp;&nbsp;
                                <div class="col-md-12">
                                    {!! Form::label('Payment Year','',['class'=>'col-md-4 control-label'])!!}
                                    <div class="col-md-6">
                                    {!! Form::select('payYear',$yearAll,'',['id'=>'payYear','class'=>'form-control']) !!}
                                        @if($errors->has('payYear'))
                                            <span class="text-danger">{{$errors->first('payYear')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <br>
                                &nbsp;&nbsp;
                                <div class="col-md-12 text-right">
                                    <div class="col-md-10 form-group">
                                        <button class="btn btn-success btn-m">Download CSV</button>
                                    </div>         
                                </div>
                        </div>
                            
                    {{Form::close()}}
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/billimport/importExport.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Import customer bill details from external source</div>
                <div class="panel-body">
                    <div class='col-md-12'>
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success" role="alert">
                            {{ Session::get('success') }}
                            </div>
                        @endif

                        @if ($message = Session::get('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ Session::get('error') }}
                            </div>
                        @endif


                       {!! Form::open(["url" =>"importExcel", "method" => "post", "class" => "form-filter form-material", 'files' => true]) !!}

                            <div class="col-md-8">
                                <div class="form-group">
                                    {!! Form::label('Document','',['class'=>'col-md-4 control-label']) !!}
                                    <div class="col-md-8">
                                        {!! Form::file('import_file',Request::old('import_file'),array('class'=>'input-sm form-control')) !!}
                                        
                                        {{ csrf_field() }}
                                    </div>
                                </div>
                            </div>
                             <div class="col-md-4">
                                <div class="form-group text-right">
                                    <button class="btn btn-success btn-md">Import File</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/billimport/importbills.blade.php
@extends('layouts.app')

@section('content')
<div class="container" >
    @if ($message = Session::get('success'))
        <div align="center" class="alert alert-success" role="alert">
            {{ Session::get('success') }}
        </div>
    @endif
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">Import Bills from P&E Server</div>
                <div class="panel-body">
                       {!! Form::open(["url" =>"/billimport/importserver", "method" => "post", "class" => "form-vertical", 'files' => true]) !!}
                                <div class="form-group {{ $errors->has('bill_date')?'has-error':'' }} {{ isset($bill_date)?'has-error':'' }}">
                                    <label class="form-label" for="category">Select Date</label>
                                    {!! Form::text('bill_date', date('d-M-Y'), array('data-field' => 'date', 'class' => 'form-control')) !!}  
                                    @if(isset($bill_date))
                                        <span class='help-block'>{{ $bill_date }}</span>
                                    @endif                              
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-success">Import Bills</button>
                                </div>
                        {!! Form::close() !!}
                   
                </div>
            </div>
        </div>
    </div>
</div>
<div id="dtbox"></div>


@endsection
  @section("extrajs")
        <script type="text/javascript">
            $(document).ready(function(){
                $("#dtbox").DateTimePicker();
            });
        </script>
    @endsection

resources/views/billimport/importprogress.blade.php
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <title>P&E Billing</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/print.css') }}">
    <link rel="stylesheet" media="print" type="text/css" href="{{ asset('css/print-hide.css') }}">
    
</head>
<body>
<div class="lightbox-loader">
    <p class="progress">
        <span class="meter"></span>
        <span class="notice">Importing Bills. Please Wait - <b></b></span>
    </p>

   <p class="center print-button-wrapper" style="top: 100px">
      <a class="print-button">VIEW/PRINT</a>
   </p>

</div>

<script type="text/javascript" src="{{ asset('jquery/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('jquery/jQuery.ajaxQueue.min.js') }}"></script>
<script>
var count = {{ $count }};
var counter = 0;
var checkInterval;

jQuery(function($){
   checkInterval = setInterval('checkStatus()', 1000);
});

function checkStatus() {
  url = "{{ route('billimport.progressCheck', ['bill_date'=>$bill_date,'count'=> $count]) }}" 
  url+= "?" + (Math.round(Math.random() * 10000))
   jQuery.ajaxQueue({
      url: url,
      type: 'get'
   }).done(function (importcount) {
      var meterLength = (importcount.count / count) * 100;

      if(importcount.count == count) {
        document.location='/billimport'
      }

      $('.lightbox-loader .progress .notice b').text(Math.floor(meterLength) + '%');
      $('.lightbox-loader .progress .meter').stop().animate({width: meterLength + '%'}, 1000, 'swing');
   });
}
</script>
</body>
</html>

resources/views/billimport/terms.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading text-center"><h3>Terms And Conditions</h3></div>
                 <center>Dummy for terms and conditions here</center>   
                <div class="panel-body">
                    <div class='col-md-10'>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection